name: PR Checks

on:
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
      fail-fast: false
    steps:
    - uses: actions/checkout@v4

    - name: Extract Version from flake.nix
      id: extract_version
      run: |
        VERSION=$(grep -oP 'version = "\K[0-9.]+(?=")' flake.nix)
        echo "Extracted version: $VERSION"
        echo "::set-output name=version::$VERSION"

    - name: Setup Nix
      uses: cachix/install-nix-action@v25

    - name: Install Flake
      run: nix profile install github:wscoble/ic-tools#${{ steps.extract_version.outputs.version }}

    - name: Test DFX Executable
      run: |
        # Assuming dfx is installed globally or available in the environment
        dfx --version
