name: PR Checks

on:
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
      fail-fast: false
    steps:
    - uses: actions/checkout@v4

    - name: Setup Nix
      uses: cachix/install-nix-action@v25

    - name: Install Flake
      run: nix profile install

    - name: Test DFX Executable
      run: |
        # Assuming dfx is installed globally or available in the environment
        dfx --version
